PracticasMVC/PracticasMVC/Models/Numero.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PracticasMVC.Models
{
    public class Numero
    {
        public int numero { get; set; }
        public List<int> multiplicaciones { get; set; }
        public Numero(int num)
        {
            this.numero = num;
            multiplicaciones = new List<int>();
        }
    }
}

PracticasMVC/PracticasMVC/Models/videos.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PracticasMVC.Models
{
    public class Videos
    {
       public String texto { get; set; }
       public String video { get; set; }
        public Videos(String t, String v)
        {
            this.texto = t;
            this.video = v;
        }

    }
}

PracticasMVC/PracticasMVC/Controllers/Practicas/PracticasController.cs
using PracticasMVC.Helper;
using PracticasMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Services;

namespace PracticasMVC.Controllers.Practicas
{
    public class PracticasController : Controller
    {
        HelperVideos videos;
        // GET: Practicas
        public ActionResult Index()
        {
            return View();
        }

        // GET: SumarNumeros
        public ActionResult SumarNumeros()
        {

            return View();
        }

        [HttpPost]
        public ActionResult SumarNumeros(int? num1, int? num2)
        {
            if(num1 is null)
            {
                num1 = 0;
            }
            if(num2 is null)
            {
                num2 = 0;
            }
            ViewBag.Suma = num1 + num2;
            return View();
        }
        // GET: NumeroDoble
        public ActionResult NumeroDoble(int? numGet)
        {
            List<int> numeros = new List<int>();
            Random random = new Random();
            int num1 = random.Next(1, 20);
            for (int i = 0; i < num1; i++)
            {
                numeros.Add(random.Next(1, 100));
            }
            ViewBag.numeros = numeros;

            if (numGet != null) {
                ViewBag.numDoble = numGet * 2;
            }
            return View();
        }
        
        public ActionResult TablaDeMultiplicar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult TablaDeMultiplicar(int? num)
        {
            List<int> numeros = new List<int>();
            if(num != null)
            {
                for (int i = 1; i < 11; i++)
                {
                    numeros.Add(i * num.Value);
                }
                ViewBag.numeros = numeros;
            } else
            {
                 
            }
            
            return View();
        }

        //GET: TablaDeMultiplicarConObjetos
        public ActionResult TablaDeMultiplicarConObjetos()
        {
            return View();
        }

        //POST: TablaDeMultiplicarConObjetos
        [HttpPost]
        public ActionResult TablaDeMultiplicarConObjetos(int? num)
        {
            Numero numero = new Numero(num.Value);
            if (num != null)
            {
                numero = new Numero(num.Value);
            } else
            {
                numero = new Numero(1);
            }

            for (int i = 1; i <= 10; i++)
            {
                numero.multiplicaciones.Add( numero.numero * i);
            }
            
            
            return View(numero);
        }

        public ActionResult TablaMultiplicarHTML()
        {
            return View();
        }

        [HttpPost]
        public ActionResult TablaMultiplicarHTML(int? num)
        {
            String html = "<table class='table table-bordered'>";
            for (int i = 1; i <= 10; i++)
            {
                int resultado = num.Value * i;
                html += "<tr><td>" + i + " x " + num + "</td><td>"+resultado+"</td></tr>";
            }
            html += "</table>";
            ViewBag.HTML = html;
            return View();
        }

        public ActionResult VideosYoutube()
        {
            return View();
        }

        [HttpPost]
        public ActionResult VideosYoutube(String video)
        {
            if(video.Trim() != "")
            {
                String html = "<iframe width = '560' height = '315'";
                if (video.IndexOf('=') > -1)
                {
                    String code = video.Split('=')[1];
                     html += " src='https://www.youtube.com/embed/"+code+"' frameborder = '0' allow = 'accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture' allowfullscreen ></ iframe >";
                } else if(video.Split('/').Length == 4)
                {
                    String[] array = video.Split('/');
                    String code = array[array.Length - 1];
                    html += " src='https://www.youtube.com/embed/" + code+ "' frameborder = '0' allow = 'accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture' allowfullscreen > </iframe>";
                } else
                {
                    html += " src='" + video + "' frameborder = '0' allow = 'accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture' allowfullscreen > </iframe>";
                }
                
                ViewBag.youtubeVideo = html;
            }
            
            return View();
        }

        // GET: ListaVideosYoutube
        public ActionResult ListaVideosYoutube()
        {
            videos = new HelperVideos();

            ViewBag.selectVideos = videos.GetVideos();
            return View();
        }

        //POST: ListaVideosYoutube
        [HttpPost]
        public ActionResult ListaVideosYoutube(String code)
        {
            videos = new HelperVideos();

            String html = "<iframe width = '560' height = '315'";
            html += " src='https://www.youtube.com/embed/" + code + "' frameborder = '0' allow = 'accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture' allowfullscreen ></ iframe >";

            ViewBag.selectVideos = videos.GetVideos();
            foreach (Videos item in ViewBag.selectVideos)
            {
                if (item.video == code)
                {
                    ViewBag.nombreVideo = item.texto;
                }
            }
            ViewBag.video = html;
            return View();
        }


        //Metodo web para funcionar con AJAX
        [WebMethod]
        public int Sumar(String numeros)
        {
            int total = 0;
            String[] nums = numeros.Split(';');
            
            foreach (String n in nums)
            {
                if(n != "") {
                    total += int.Parse(n);
                }
                
            }
            return total;
        }
    }
}

PracticasMVC/PracticasMVC/Views/Practicas/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Índice</h2>

<ul>
    <li>
        @Html.ActionLink("Sumar Números","SumarNumeros","Practicas")
    </li>
    <li>
        @Html.ActionLink("Número Doble", "NumeroDoble", "Practicas")
    </li>
    <li>
        @Html.ActionLink("Tabla De Multiplicar", "TablaMultiplicar", "Practicas")
    </li>
    <li></li>
    <li></li>
    <li></li>
</ul>

PracticasMVC/PracticasMVC/Views/Practicas/ListaVideosYoutube.cshtml
@model PracticasMVC.Models.Videos
@{
    ViewBag.Title = "ListaVideosYoutube";
}

<h2>ListaVideosYoutube</h2>

<form method="post">
    <select name="code" class="form-control bootstrap-select>
        @foreach (PracticasMVC.Models.Videos v in ViewBag.selectVideos)
        {
            <option value="@v.video">@v.texto</option>
        }
    </select>
    <br />
    <button type="submit" class="form-control">Visualizar</button>
</form>
<br />

<h2>@ViewBag.nombreVideo</h2>
@Html.Raw(ViewBag.video)

PracticasMVC/PracticasMVC/Views/Practicas/NumeroDoble.cshtml
@{
    ViewBag.Title = "Numero Doble";
}

@{
    Random random = new Random();
}
<h2>Numero Doble</h2>

<ul>
    @foreach (int n in ViewBag.numeros)
    {
        <li>@Html.ActionLink(n.ToString(),"NumeroDoble","Practicas", new { numGet = n},null)</li>
    }
</ul>

@if(ViewBag.numDoble != null)
{
<h1>@ViewBag.numDoble</h1>
}

PracticasMVC/PracticasMVC/Views/Practicas/SumarNumeros.cshtml
@{
    ViewBag.Title = "SumarNumeros";
}
@{ }
<script src="~/Scripts/jquery-1.10.2.js"></script>
<script>
    $(document).ready(function () {
        var num = 3;
        
        $("#add").click(function () {
            $("#moreElements").append("<div class='row'><div class='col-md-5 col-md-offset-3'> <label>Numero" + num + ": &nbsp;</label><input type = 'number' name='num" + num + "' /></div></div>");
            num++;     
        });

        $("#sumar").click(function () {
            var valores = { numeros: getAllValues() }; //Parametros del método al que se llama
            $.ajax({
                method: "POST",
                url: '@Url.Action("Sumar")', //Llamada del método C# partiendo desde la ruta que acciona el GET
                data: valores,
                success: function (algo) {
                    console.log(algo);
                    $("#resultado").text(algo);
                }
            });
        });

    });
    //Obtiene todos los valores
    function getAllValues() {
        var numbers = "";
        $("input").each(function (index) {
            numbers += $(this).val() + ";";
        })
        return numbers;
    }

</script>

<h2>Sumar Números</h2>
<form method="post">
    <div class="row">
        <div class="col-md-5 col-md-offset-3">
            <label>Numero1:</label>
            <input type="number" name="num1" />
        </div>
    </div>
    <div class="row">
        <div class="col-md-5 col-md-offset-3">
            <label>Numero2: </label>
            <input type="number" name="num2" />
        </div>
    </div>
    <div id="moreElements">

    </div>
    <div class="row">
        <button type="button" id="add">Añadir</button>
    </div>
    <div class="row">
        <div class="col-md-5 col-md-offset-3">
            <button type="button" id="sumar">Sumar</button>
        </div>
    </div>
</form>

<h1 id="resultado">@ViewBag.Suma</h1>

PracticasMVC/PracticasMVC/Views/Practicas/TablaDeMultiplicar.cshtml
@{
    ViewBag.Title = "TablaDeMultiplicar";
}
<style>
    td {
        border: solid 1px;
        padding: 10px;
    }
    th {
        border: solid 1px;
    }
</style>
<h2>Tabla de Multiplicar</h2>

<form method="post">
    <div class="row">
        <div class="col-md-5">
            <label>Numero: </label>
            <input type="number" min="1" name="num" class="form-control" />
        </div>
    </div>
    <div class="row">
        <div class="col-md-1">
            <button type="submit" class="form-control">Tabla</button>
        </div>
    </div>
</form>
<br />
@if (ViewBag.numeros != null)
{
    <table>
        <tr>
            <th colspan="2"> Tabla de Multiplicar</th>
        </tr>
    @for (int i = 1; i < 11; i++)
    {
        <tr>
            <td>@i</td>
            <td>@ViewBag.numeros[i-1]</td>
        </tr>
    }

    </table>
}

PracticasMVC/PracticasMVC/Views/Practicas/TablaDeMultiplicarConObjetos.cshtml
@model PracticasMVC.Models.Numero
@{
    ViewBag.Title = "TablaDeMultiplicarConObjetos";
}

<style>
    td {
        border: solid 1px;
        padding: 10px;
    }

    th {
        border: solid 1px;
    }
</style>


<h2>TablaDeMultiplicarConObjetos</h2>

<form method="post">
    <div class="row">
        <div class="col-md-5">
            <label>Numero: </label>
            <input type="number" min="1" name="num" class="form-control" />
        </div>
    </div>
    <div class="row">
        <div class="col-md-1">
            <button type="submit" class="form-control">Tabla</button>
        </div>
    </div>
</form>
<br />
<br />
@if (@Model != null)
{

<table>
    <tr>
        <th colspan="2"> Tabla de Multiplicar</th>
    </tr>

    @for (int i = 1; i <= 10; i++)
    {
        <tr>
            <td>@i x @Model.numero</td>
            <td>@Model.multiplicaciones[i-1]</td>
        </tr>
    }

</table>
}

PracticasMVC/PracticasMVC/Views/Practicas/TablaMultiplicarHTML.cshtml
@{
    ViewBag.Title = "TablaMultiplicarHTML";
}

<h2>TablaMultiplicarHTML</h2>
<form method="post">
    <div class="row">
        <div class="col-md-5">
            <label>Numero: </label>
            <input type="number" min="1" name="num" class="form-control" />
        </div>
    </div>
    <div class="row">
        <div class="col-md-1">
            <button type="submit" class="form-control">Tabla</button>
        </div>
    </div>
</form>
<br />
<br />
@Html.Raw(ViewBag.HTML)

PracticasMVC/PracticasMVC/Views/Practicas/VideosYoutube.cshtml
@{
    ViewBag.Title = "Videos de Youtube";
}

<h2>VideosYoutube</h2>
<form method="post">
    <div class="row">
        <div class="col-md-5">
            <input type="text" name="video" class="form-control" />
            <button type="submit" class="form-control">Ver video</button>
        </div>
    </div>
</form>
@Html.Raw(ViewBag.youtubeVideo)

PracticasMVC/PracticasMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Scripts/bootstrap-select.min.js"></script>
    <link href="~/Content/bootstrap-select.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>